package esfe.presentacion.contabilidad.tipocuenta;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import esfe.utils.WindowConfig;

import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

public class CrearCuentaForm extends JDialog {

    private JPanel mainPanel;
    // ─── LIMPIEZA: Se eliminaron txtCodigo y txtEstado ───
    private JTextField txtNombre;  // Mapea a NombreTipo
    private JTextField txtTipo;    // Mapea a Naturaleza ('D' o 'H')
    private JButton btnGuardar;
    private JButton btnCancelar;
    private JLabel lblTitulo;

    public CrearCuentaForm(TipoCuenta padre) {
        super(padre, true);
        setTitle("Nueva Cuenta");
        setContentPane(mainPanel);
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        WindowConfig.configurarVentana(this);
        setLocationRelativeTo(padre);

        btnCancelar.addActionListener(e -> dispose());
        btnGuardar.addActionListener(e -> guardarRegistro());
    }

    private void guardarRegistro() {
        String nombre = txtNombre.getText().trim();
        String tipoStr = txtTipo.getText().trim();

        // Validamos únicamente los campos que sí se van a guardar
        if (nombre.isEmpty() || tipoStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete los campos Nombre y Tipo.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String url = "jdbc:sqlserver://ContabilidadESFE.mssql.somee.com:1433;databaseName=ContabilidadESFE;encrypt=true;trustServerCertificate=true;";
        String usuario = "ContabilidadGab_SQLLogin_1";
        String password = "a7l6kuot7x";

        // SQL Server genera el TipoCuentaId automáticamente
        String sql = "INSERT INTO TiposCuenta (NombreTipo, Naturaleza) VALUES (?, ?)";

        try {
            // Mapeo automático de Naturaleza ('D' o 'H')
            char naturalezaChar = 'D';
            if (!tipoStr.isEmpty()) {
                char inicial = Character.toUpperCase(tipoStr.charAt(0));
                if (inicial == 'H' || inicial == 'P' || inicial == 'I' || inicial == 'A') {
                    naturalezaChar = 'H';
                }
            }

            Connection con = DriverManager.getConnection(url, usuario, password);
            if (con != null) {
                PreparedStatement ps = con.prepareStatement(sql);

                ps.setString(1, nombre);
                ps.setString(2, String.valueOf(naturalezaChar));

                int filasAfectadas = ps.executeUpdate();
                ps.close();
                con.close();

                if (filasAfectadas > 0) {
                    JOptionPane.showMessageDialog(this, "¡Registro guardado con éxito en Somee!");
                    dispose();
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error de SQL Server: " + ex.getMessage(), "Error al Guardar", JOptionPane.ERROR_MESSAGE);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Nombre Tipo");
        mainPanel.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtNombre = new JTextField();
        mainPanel.add(txtNombre, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtTipo = new JTextField();
        mainPanel.add(txtTipo, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Crear Nueva Cuenta");
        mainPanel.add(label2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnGuardar = new JButton();
        btnGuardar.setText("Guardar");
        mainPanel.add(btnGuardar, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCancelar = new JButton();
        btnCancelar.setText(" Cancelar");
        mainPanel.add(btnCancelar, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Naturaleza");
        mainPanel.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}